# Skin dermatology

- dataset: https://www.kaggle.com/datasets/kmader/skin-cancer-mnist-ham10000?resource=download

In [1]:
%pip install --upgrade pip setuptools wheel
# PyTorch (CPU); if you already have torch with CUDA, you can skip this CPU line
%pip install torch torchvision torchaudio --upgrade
# Vision + metrics deps
%pip install timm scikit-learn matplotlib pandas opencv-python-headless tqdm seaborn
# Try pytorch-grad-cam first; if not available for your Python, we'll fallback to torchcam
try:
    %pip install pytorch-grad-cam
    print("Installed pytorch-grad-cam.")
except Exception as e:
    print("Could not install pytorch-grad-cam:", e)
    %pip install torchcam
    print("Installed torchcam as fallback.")


Note: you may need to restart the kernel to use updated packages.
  Using cached torch-2.9.0-cp312-cp312-win_amd64.whl.metadata (30 kB)
  Using cached torchvision-0.24.0-cp312-cp312-win_amd64.whl.metadata (5.9 kB)
  Using cached torchaudio-2.9.0-cp312-cp312-win_amd64.whl.metadata (6.9 kB)
Using cached torch-2.9.0-cp312-cp312-win_amd64.whl (109.3 MB)
Using cached torchvision-0.24.0-cp312-cp312-win_amd64.whl (4.3 MB)
Using cached torchaudio-2.9.0-cp312-cp312-win_amd64.whl (665 kB)

  Attempting uninstall: torch

    Found existing installation: torch 2.4.1+cpu

   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [torch]
   ---------------------------------------

ERROR: Could not find a version that satisfies the requirement pytorch-grad-cam (from versions: none)
ERROR: No matching distribution found for pytorch-grad-cam


In [5]:
import sys, platform
print("Python:", sys.version)
print("Exe   :", sys.executable)
print("OS    :", platform.platform())


Python: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
Exe   : c:\Users\Nitro\OneDrive\Desktop\skin-dermotology\venv\Scripts\python.exe
OS    : Windows-11-10.0.26200-SP0


In [3]:
%pip install --upgrade pip setuptools wheel

# PyTorch (CPU build = simplest on Windows/macOS; works everywhere)
%pip install --index-url https://download.pytorch.org/whl/cpu \
  torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1

# Core libs
%pip install timm==1.0.9 scikit-learn pandas matplotlib tqdm seaborn opencv-python-headless pillow

# Optional: Grad-CAM (try pytorch-grad-cam; if it fails we’ll fall back to torchcam later)
try:
    %pip install pytorch-grad-cam
    print("Installed pytorch-grad-cam")
except Exception as e:
    print("Could not install pytorch-grad-cam:", e)
    %pip install torchcam
    print("Installed torchcam (fallback)")


Note: you may need to restart the kernel to use updated packages.
Looking in indexes: https://download.pytorch.org/whl/cpu
  Using cached https://download.pytorch.org/whl/cpu/torch-2.4.1%2Bcpu-cp312-cp312-win_amd64.whl (201.7 MB)
  Using cached https://download.pytorch.org/whl/cpu/torchvision-0.19.1%2Bcpu-cp312-cp312-win_amd64.whl (1.3 MB)
  Using cached https://download.pytorch.org/whl/cpu/torchaudio-2.4.1%2Bcpu-cp312-cp312-win_amd64.whl (2.4 MB)

  Attempting uninstall: torch

    Found existing installation: torch 2.9.0

   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [torch]
   ---------------------------------------- 0/3 [torch]
   -------------------

ERROR: Could not find a version that satisfies the requirement pytorch-grad-cam (from versions: none)
ERROR: No matching distribution found for pytorch-grad-cam


In [4]:
import sys, torch, torchvision
print("Exe:", sys.executable)
print("torch:", torch.__version__, "| torchvision:", torchvision.__version__)
print("Path torch:", torch.__file__)


Exe: c:\Users\Nitro\OneDrive\Desktop\skin-dermotology\venv\Scripts\python.exe
torch: 2.4.1+cpu | torchvision: 0.19.1+cpu
Path torch: c:\Users\Nitro\OneDrive\Desktop\skin-dermotology\venv\Lib\site-packages\torch\__init__.py


In [6]:
import os, random, shutil, pathlib, json
import numpy as np
import pandas as pd
from PIL import Image
from tqdm import tqdm

import torch, torch.nn as nn
from torch.utils.data import DataLoader, WeightedRandomSampler
from torchvision import datasets, transforms
import timm

from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

# Grad-CAM availability flags
HAS_PTCAM = False
HAS_TORCHCAM = False
try:
    from pytorch_grad_cam import GradCAM
    from pytorch_grad_cam.utils.image import show_cam_on_image
    HAS_PTCAM = True
except Exception:
    try:
        from torchcam.methods import GradCAM as TorchGradCAM
        HAS_TORCHCAM = True
    except Exception:
        pass

# Repro & training settings
SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)

IMG_SIZE    = 224
BATCH_SIZE  = 32
EPOCHS      = 12        # increase later if you want
LR          = 3e-4
CONF_THRESH = 0.6
DEVICE      = "cuda" if torch.cuda.is_available() else "cpu"

# HAM10000 7 classes
CLASSES = ["akiec","bcc","bkl","df","mel","nv","vasc"]

print("Device       :", DEVICE)
print("CAM backend  :", "pytorch-grad-cam" if HAS_PTCAM else ("torchcam" if HAS_TORCHCAM else "none"))


c:\Users\Nitro\OneDrive\Desktop\skin-dermotology\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Device       : cpu
CAM backend  : none


In [7]:
# Folder that contains: HAM10000_metadata.csv, HAM10000_images_part_1, HAM10000_images_part_2
ROOT_DIR = r"C:\Users\Nitro\OneDrive\Desktop\skin-dermotology\dataset"  # <-- EDIT if your path differs

META_CSV = os.path.join(ROOT_DIR, "HAM10000_metadata.csv")
PART1    = os.path.join(ROOT_DIR, "HAM10000_images_part_1")
PART2    = os.path.join(ROOT_DIR, "HAM10000_images_part_2")

for p in [META_CSV, PART1, PART2]:
    assert os.path.exists(p), f"Missing: {p}"

IMG_DIRS = [PART1, PART2]
print("ROOT_DIR:", ROOT_DIR)


ROOT_DIR: C:\Users\Nitro\OneDrive\Desktop\skin-dermotology\dataset


In [8]:
OUT_SPLIT = "data/split"

# Create folders
for split in ["train","val","test"]:
    for c in CLASSES:
        pathlib.Path(os.path.join(OUT_SPLIT, split, c)).mkdir(parents=True, exist_ok=True)

# Load metadata and keep only our 7 classes
meta = pd.read_csv(META_CSV)
meta = meta[meta["dx"].isin(CLASSES)].copy()

# Map image_id → absolute path
def path_for(img_id: str):
    name = img_id + ".jpg"
    for d in IMG_DIRS:
        p = os.path.join(d, name)
        if os.path.exists(p): return p
    return None

meta["img_path"] = meta["image_id"].apply(path_for)
meta = meta.dropna(subset=["img_path"]).reset_index(drop=True)

# Split by lesion_id (prevents patient/image leakage)
lesions = meta["lesion_id"].dropna().unique().tolist()
random.shuffle(lesions)
n = len(lesions)
train_ids = set(lesions[:int(0.70*n)])
val_ids   = set(lesions[int(0.70*n):int(0.85*n)])
test_ids  = set(lesions[int(0.85*n):])

def which_split(lid):
    return "train" if lid in train_ids else ("val" if lid in val_ids else "test")

meta["split"] = meta["lesion_id"].apply(which_split)

# Copy files into data/split/<split>/<class>/image.jpg
for _, r in tqdm(meta.iterrows(), total=len(meta), desc="Copying → data/split"):
    dst = os.path.join(OUT_SPLIT, r["split"], r["dx"], os.path.basename(r["img_path"]))
    if not os.path.exists(dst):
        shutil.copy2(r["img_path"], dst)

print(meta["split"].value_counts())
print("Per-class counts:\n", meta["dx"].value_counts())


Copying → data/split: 100%|██████████| 10015/10015 [00:13<00:00, 717.32it/s]

split
train    7018
val      1512
test     1485
Name: count, dtype: int64
Per-class counts:
 dx
nv       6705
mel      1113
bkl      1099
bcc       514
akiec     327
vasc      142
df        115
Name: count, dtype: int64


In [9]:
from collections import Counter

# Transforms
train_tfms = transforms.Compose([
    transforms.RandomResizedCrop(IMG_SIZE, scale=(0.8,1.0)),
    transforms.RandomHorizontalFlip(),
    transforms.ColorJitter(0.1,0.1,0.1,0.05),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225]),
])
eval_tfms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225]),
])

# Datasets
train_ds = datasets.ImageFolder(os.path.join(OUT_SPLIT,"train"), transform=train_tfms)
val_ds   = datasets.ImageFolder(os.path.join(OUT_SPLIT,"val"),   transform=eval_tfms)
test_ds  = datasets.ImageFolder(os.path.join(OUT_SPLIT,"test"),  transform=eval_tfms)
classes  = train_ds.classes
print("Classes:", classes)

# Weighted sampler to reduce class imbalance
cnt = Counter([y for _, y in train_ds.samples])
class_count = np.array([cnt[i] for i in range(len(classes))])
weights = 1.0 / np.clip(class_count, 1, None)
sample_w = np.array([weights[y] for _, y in train_ds.samples], dtype=np.float32)
sampler  = WeightedRandomSampler(sample_w, num_samples=len(sample_w), replacement=True)

# Loaders
train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, sampler=sampler, num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)
test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

# Sanity check
xb, yb = next(iter(train_loader))
print("Batch:", xb.shape, yb.shape)


Classes: ['akiec', 'bcc', 'bkl', 'df', 'mel', 'nv', 'vasc']
Batch: torch.Size([32, 3, 224, 224]) torch.Size([32])


In [10]:
from tqdm import tqdm

model = timm.create_model("efficientnet_b0", pretrained=True, num_classes=len(classes)).to(DEVICE)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=LR)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)

def run_epoch(loader, train=False):
    model.train(train)
    total=correct=0; losses=[]
    for x,y in tqdm(loader, leave=False):
        x,y = x.to(DEVICE), y.to(DEVICE)
        with torch.set_grad_enabled(train):
            logits = model(x); loss = criterion(logits, y)
        if train:
            optimizer.zero_grad(); loss.backward(); optimizer.step()
        total += y.size(0)
        correct += (logits.argmax(1)==y).sum().item()
        losses.append(loss.item())
    return float(np.mean(losses)), correct/total

best_val = 0.0
for epoch in range(1, EPOCHS+1):
    tr_loss, tr_acc = run_epoch(train_loader, train=True)
    va_loss, va_acc = run_epoch(val_loader,   train=False)
    scheduler.step()
    print(f"Epoch {epoch:02d} | Train {tr_acc:.3f}/{tr_loss:.3f}  Val {va_acc:.3f}/{va_loss:.3f}")
    if va_acc > best_val:
        best_val = va_acc
        torch.save({"model":model.state_dict(),"classes":classes}, "best_model.pt")
        print("  ✓ saved best_model.pt")


Epoch 01 | Train 0.738/0.860  Val 0.775/0.734
  ✓ saved best_model.pt


Epoch 02 | Train 0.875/0.365  Val 0.819/0.499
  ✓ saved best_model.pt


Epoch 03 | Train 0.921/0.227  Val 0.871/0.401
  ✓ saved best_model.pt


Epoch 04 | Train 0.939/0.170  Val 0.886/0.368
  ✓ saved best_model.pt


Epoch 05 | Train 0.952/0.140  Val 0.908/0.437
  ✓ saved best_model.pt


Epoch 06 | Train 0.965/0.104  Val 0.921/0.273
  ✓ saved best_model.pt


Epoch 07 | Train 0.980/0.069  Val 0.936/0.230
  ✓ saved best_model.pt


Epoch 08 | Train 0.984/0.050  Val 0.944/0.223
  ✓ saved best_model.pt


Epoch 09 | Train 0.985/0.044  Val 0.946/0.229
  ✓ saved best_model.pt


Epoch 10 | Train 0.989/0.036  Val 0.954/0.188
  ✓ saved best_model.pt


Epoch 11 | Train 0.993/0.025  Val 0.954/0.204
  ✓ saved best_model.pt


Epoch 12 | Train 0.991/0.029  Val 0.957/0.185
  ✓ saved best_model.pt


In [11]:
ckpt = torch.load("best_model.pt", map_location=DEVICE)
model.load_state_dict(ckpt["model"]); model.eval()
classes = ckpt["classes"]

def collect(loader):
    outs=[]; ys=[]
    with torch.no_grad():
        for x,y in loader:
            outs.append(model(x.to(DEVICE)).cpu()); ys.append(y)
    return torch.cat(outs), torch.cat(ys)

logits, y = collect(test_loader)
probs = logits.softmax(1).numpy()
y_true = y.numpy()
y_pred = probs.argmax(1)

print("\nClassification report:\n",
      classification_report(y_true, y_pred, target_names=classes, digits=3))

try:
    y_oh = np.eye(len(classes))[y_true]
    auroc = roc_auc_score(y_oh, probs, average="macro", multi_class="ovr")
    print("Macro AUROC:", round(auroc,3))
except Exception as e:
    print("AUROC note:", e)

print("Confusion matrix:\n", confusion_matrix(y_true, y_pred))


C:\Users\Nitro\AppData\Local\Temp\ipykernel_22704\753640660.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load("best_model.pt", map_location=DEVICE)



Classification report:
               precision    recall  f1-score   support

       akiec      0.886     0.909     0.897        77
         bcc      0.896     0.980     0.936       149
         bkl      0.920     0.914     0.917       291
          df      0.933     0.800     0.862        35
         mel      0.898     0.865     0.881       296
          nv      0.975     0.974     0.975      1850
        vasc      0.865     0.970     0.914        33

    accuracy                          0.952      2731
   macro avg      0.911     0.916     0.912      2731
weighted avg      0.952     0.952     0.952      2731

Macro AUROC: 0.993
Confusion matrix:
 [[  70    3    2    0    1    1    0]
 [   1  146    1    0    1    0    0]
 [   2    3  266    1    7   12    0]
 [   1    3    2   28    0    1    0]
 [   2    2    5    0  256   31    0]
 [   3    6   13    1   20 1802    5]
 [   0    0    0    0    0    1   32]]


In [12]:
def predict_image(image_path, conf_thresh=0.6):
    ckpt = torch.load("best_model.pt", map_location=DEVICE)
    classes = ckpt["classes"]
    mdl = timm.create_model("efficientnet_b0", pretrained=False, num_classes=len(classes)).to(DEVICE)
    mdl.load_state_dict(ckpt["model"]); mdl.eval()

    tfm = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225]),
    ])
    img = Image.open(image_path).convert("RGB")
    x = tfm(img).unsqueeze(0).to(DEVICE)
    with torch.no_grad():
        prob = mdl(x).softmax(1).squeeze(0).cpu().numpy()
    idx = int(prob.argmax()); conf = float(prob[idx])
    return {
        "prediction": "ABSTAIN" if conf < conf_thresh else classes[idx],
        "confidence": conf,
        "probs": {c: float(p) for c,p in zip(classes, prob)}
    }

# Example usage:
# import pathlib
# sample = next(iter(pathlib.Path("data/split/test").rglob("*.jpg")))
# print(sample, predict_image(str(sample)))


In [13]:
if HAS_PTCAM:
    os.makedirs("outputs/cam_samples", exist_ok=True)

    # inverse normalization for display
    inv = transforms.Normalize(
        mean=[-m/s for m,s in zip([0.485,0.456,0.406],[0.229,0.224,0.225])],
        std=[1/s for s in [0.229,0.224,0.225]]
    )

    target_layer = model.conv_head if hasattr(model, "conv_head") else list(model.children())[-1]
    cam = GradCAM(model=model, target_layers=[target_layer], use_cuda=False)

    saved=0
    for x,_ in test_loader:
        x = x.to(DEVICE)
        with torch.no_grad():
            logits = model(x)
            p = logits.softmax(1)
            conf, pred = p.max(1)
        for i in range(min(8, x.size(0))):
            img = x[i].detach().cpu()
            np_img = inv(img).clamp(0,1).permute(1,2,0).numpy().astype(np.float32)
            label = "ABSTAIN" if conf[i].item()<CONF_THRESH else classes[pred[i].item()]
            grayscale_cam = cam(input_tensor=x[i].unsqueeze(0), targets=None)[0]
            overlay = show_cam_on_image(np_img, grayscale_cam, use_rgb=True)
            Image.fromarray((overlay*255).astype(np.uint8)).save(f"outputs/cam_samples/cam_{saved}_{label}.jpg")
            saved += 1
        if saved>=16: break

    print("Saved CAMs → outputs/cam_samples/ (pytorch-grad-cam)")
else:
    print("pytorch-grad-cam not available; use the torchcam cell if installed.")


pytorch-grad-cam not available; use the torchcam cell if installed.


In [14]:
if HAS_TORCHCAM:
    import matplotlib.pyplot as plt
    os.makedirs("outputs/cam_samples", exist_ok=True)

    # choose last Conv2d as target
    target_layer = None
    for m in reversed(list(model.modules())):
        if isinstance(m, torch.nn.Conv2d):
            target_layer = m; break
    cam_extractor = TorchGradCAM(model, target_layer=target_layer)

    inv = transforms.Normalize(
        mean=[-m/s for m,s in zip([0.485,0.456,0.406],[0.229,0.224,0.225])],
        std=[1/s for s in [0.229,0.224,0.225]]
    )

    saved=0
    model.eval()
    for x,_ in test_loader:
        x = x.to(DEVICE)
        scores = model(x)
        for i in range(min(8, x.size(0))):
            cls = int(scores[i].argmax().item())
            cam_map = cam_extractor(class_idx=cls, scores=scores)[i].detach().cpu()  # HxW
            img = x[i].detach().cpu()
            img_disp = inv(img).clamp(0,1).permute(1,2,0).numpy()
            cam_np = torch.nn.functional.interpolate(
                cam_map.unsqueeze(0).unsqueeze(0),
                size=(img_disp.shape[0], img_disp.shape[1]),
                mode="bilinear", align_corners=False
            ).squeeze().numpy()
            plt.figure(figsize=(3,3)); plt.axis('off')
            plt.imshow(img_disp); plt.imshow(cam_np, alpha=0.4); plt.title(CLASSES[cls])
            plt.savefig(f"outputs/cam_samples/cam_{saved}_{CLASSES[cls]}.jpg",
                        bbox_inches='tight', pad_inches=0)
            plt.close(); saved += 1
        if saved>=16: break

    print("Saved CAMs → outputs/cam_samples/ (torchcam)")
else:
    print("torchcam not available; CAMs skipped.")


torchcam not available; CAMs skipped.
